### PR TITLE
SONAR-13530 Prevent default when button is disabled

### PR DESCRIPTION
**Pull request by jeremy-davis-sonarsource**
...description

**Checklist**

* [x] Functional validation
* ~Documentation update~
* [x] Update changelog

### CODE REVIEW

**Review by gregaubert — APPROVED** [review]
:+1:

**Comment by jeremy-davis-sonarsource** [comment]
BTW @gregaubert, it'll fix https://jira.sonarsource.com/browse/SC-2149. Want me to reference it in the commit? Or we could just delete it, I guess...

**Comment by gregaubert** [comment]
Na it's fine, I'll just close it with a reference to your ticket

**Review by wouter-admiraal-sonarsource — APPROVED** [review]
LGTM! Such a simple fix, such a big impact 😅 .

**Pull request merged**
