### PR TITLE
:arrow_up: bump version

### PR DESCRIPTION
**Pull request by siegfried-ehret-sonarsource**
I failed to publish a good version, just did `yarn publish` without giving it the tar.gz file...
Let's do it again...
Sorry.

### CODE REVIEW

**Comment by gregaubert** [comment]
You could easily do releases by using `yarn release` if you setup your `npmrc` files correctly.

**Review by gregaubert — APPROVED** [review]
Seems good! But please add the version number in the commit name! And don't forget to tag it.

**Comment by wouter-admiraal-sonarsource** [comment]
Sorry, late to the party, but: doesn't the `script/release.sh` helper work for you? It has some safeguards in place to revert in case there's an issue.

**Comment by siegfried-ehret-sonarsource** [comment]
I was not aware of it but I am now and things will be better next time.

**Pull request merged**
