### PR TITLE
SC-1059 Fix styling of disabled options in Select

### PR DESCRIPTION
**Pull request by gregaubert**
Relates to https://github.com/SonarSource/sonarcloud-core/pull/238

**Checklist**

* [x] Functional validation
* [x] Update changelog

### CODE REVIEW

**Comment by siegfried-ehret-sonarsource** [comment]
I think it's hard to tell the difference between the enabled and disabled elements:

Screenshot 2019-10-21 at 10 21 50

**Comment by gregaubert** [comment]
Seeing the styling it's because you are not looking at it with the right version of sonar-ui-common

**Comment by siegfried-ehret-sonarsource** [comment]
Got it !
Can we do something about the text and ❔ sign alignment ?

Screenshot 2019-10-22 at 08 58 12

**Comment by gregaubert** [comment]
Sure I'll have a look

**Review by siegfried-ehret-sonarsource — APPROVED** [review]

**Comment by gregaubert** [comment]
@philippe-perrin-sonarsource I'll be merging this and do a release, which will require you to cherry-pick a commit from https://github.com/SonarSource/sonarcloud-core/pull/238: SC-1059 Update style of disabled select options

**Pull request merged**
