### PR TITLE
SC-1819 Rework SC user onboarding

### PR DESCRIPTION
**Pull request by jonathan-weibel-sonarsource**
https://jira.sonarsource.com/browse/SC-1819

**Checklist**

* [ ] Functional validation
* [ ] Documentation update
* [ ] Update changelog

### CODE REVIEW

**Comment by jonathan-weibel-sonarsource** [comment]
I wonder whether the snapshots are helpful here. Maybe I should just drop these UT.

**Comment by jonathan-weibel-sonarsource** [comment]
@jeremy-davis-sonarsource Do these 2 icons (Join orga & Browse orga) would make sense for SQ? Else, I move the code to sonarcloud-core.

**Comment by siegfried-ehret-sonarsource** [comment]
@jonathan-weibel-sonarsource about the tests, you can have a look at https://github.com/SonarSource/sonarcloud-core/blob/master/server/sonar-web/src/main/js/apps/projectAnalysisMethod/components/__tests__/EligibilityOK-test.tsx#L18-L21 to make them better and have useful snapshots.

**Comment by jonathan-weibel-sonarsource** [comment]
I close this PR that is not relevant. I moved the icons to sonarcloud-core.

**Pull request closed without merging**
