### PR TITLE
Update icon for ClipboardIconButton

### PR DESCRIPTION
**Pull request by siegfried-ehret-sonarsource**
Needed for MMF-1781, as a starting point to revamp the copy icon for SonarCloud. See icons at the end of points 1 and 2 in this mockup screen:

FirstAnalysisTutorial_3 2-BitBucket--create-pipeline-step2

See: 

* https://jira.sonarsource.com/browse/MMF-1781

**Checklist**

* [x] Write/update ITs
* [ ] Functional validation
* [ ] Documentation update
* [x] Update changelog

### CODE REVIEW

**Review by gregaubert — COMMENTED** [review]
Looks good, just one question though: should we really allow to customize ? or just change the icon altogether? If we allow to customize, it means we can end up with lot of different visual for the copy icon button, is it really something we want to allow ?

**Comment by siegfried-ehret-sonarsource** [comment]
WDYT @wouter-admiraal-sonarsource @jeremy-davis-sonarsource @philippe-perrin-sonarsource ?
The existing icon was given by @mathieu-cutivel-sonarsource.

**Comment by gregaubert** [comment]
@laurawacrenier @mathieu-cutivel-sonarsource is it really important to have a different copy icon for SQ and SC ? Or can you guys agree on one of them that we use for both products ?

**Comment by laurawacrenier** [comment]
> @laurawacrenier @mathieu-cutivel-sonarsource is it really important to have a different copy icon for SQ and SC ? Or can you guys agree on one of them that we use for both products ?

No, we should use the same. I decided to change it because the first one was not following our current icon style for action icons (should be solid, not outlined). 

@mathieu-cutivel-sonarsource it looks like there is a flaw in our design review process because I never saw this icon before and was very surprised to find something like that already existed. Let's talk about it when you're back.

**Comment by siegfried-ehret-sonarsource** [comment]
Thanks @laurawacrenier, I'll update it.

**Comment by gregaubert** [comment]
Thanks for you input @laurawacrenier ! So let's change the icon altogether and not make the button customizable! :)

**Review by gregaubert — APPROVED** [review]
:+1:

**Pull request merged**
