### PR TITLE
SONAR-13479 Add Chevrons icon

### PR DESCRIPTION
**Pull request by jeremy-davis-sonarsource**
A new icon for MMF-2049.

**Checklist**

* [x] Functional validation
* ~Documentation update~
* [x] Update changelog

### CODE REVIEW

**Review by gregaubert — COMMENTED** [review]
Looks good but what's the diff with `Chevron{Down,Up,Right,Left}Icon.tsx` ?

**Review by philippe-perrin-sonarsource — COMMENTED** [review]
What Greg said. Couldn't you use left+right?

**Comment by jeremy-davis-sonarsource** [comment]
icons are 16x16, so putting two chevrons side-by-side would not be the same.
It's basically asking if we can't use dash + right chevron instead of an arrow :smile:

**Review by gregaubert — APPROVED** [review]
Indeed! Lgtm!

**Review by philippe-perrin-sonarsource — APPROVED** [review]
LGTM

**Pull request merged**
