### PR TITLE
SONAR-11714 Update badge styles

### PR DESCRIPTION
**Pull request by wouter-admiraal-sonarsource**
See https://github.com/SonarSource/sonar-enterprise/pull/1930

### CODE REVIEW

**Review by gregaubert — COMMENTED** [review]
Seems good on this side.
I know that you are not done yet on your sonar-enterprise PR but I just wanted to highlight that there are still usages of `.outline-badge` in governance.

**Review by gregaubert — APPROVED** [review]

**Comment by wouter-admiraal-sonarsource** [comment]
> Seems good on this side.
> I know that you are not done yet on your sonar-enterprise PR but I just wanted to highlight that there are still usages of `.outline-badge` in governance.

Yes, thanks. I still have to through all the extensions. This badge cleanup is pretty involved 😅 . But we're moving from 11 styles of badges to only 5, which will be much easier to manage (and understand).

**Comment by philippe-perrin-sonarsource** [comment]
General comment : maybe we should add a "What to improve section" to README saying that we rely on css style that are declared in sonar-web ?

**Review by philippe-perrin-sonarsource — APPROVED** [review]

**Comment by gregaubert** [comment]
Like this @philippe-perrin-sonarsource ? :smile: 
image

Feel free to add things in there as we go!

**Comment by philippe-perrin-sonarsource** [comment]
OK. Actually I meant : maybe we should add a SECTION to the "What to improve section" of the README saying that we should not rely on css style that are declared in sonar-web ? Generaly speaking, make that lib a real independant lib.

**Pull request merged**
